# Generated by Django 5.2.7 on 2025-10-09 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_student_parent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='marks_obtained',
            new_name='marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.course'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.exam'),
        ),
    ]
